### ISSUE TITLE
Please add a screenshot and spec requirements (minimum: FC version, Qt version etc....) 

### ISSUE THREAD

**Issue by luzpaz** [Axeia/FreeCAD-Color-Fetcher#1]

**Comment by Axeia** [comment]
The FC version was specified in the .FCMacro file as  "FreeCAD >= v0.20" which what I had tested it with. Due to your 'issue' I tried some other versions and I cannot seem to make it work in versions in older than v0.19. I had to make a small change to make it work in v0.19 but that's covered now :)

Initially it was just a quick script for MisterMakerNL as I didn't quite understand what he wanted and just made something to have a starting point to iterate from. 

I'll add a proper README.md to the github either today or tomorrow along with a screenshot as requested. Is there any reason in particular you need to know the Qt version? (it just uses PySide2 which seems to be Qt 5.12+)

**Comment by luzpaz** [comment]
Thanks so much for all your work. You experimentations will help propel more refinements in FreeCAD UI/UX for sure!:pray: 

> Is there any reason in particular you need to know the Qt version? (it just uses PySide2 which seems to be Qt 5.12+)

Indeed. There is work toward migrating FC to Qt6 (https://github.com/FreeCAD/FreeCAD/issues/6992). In conjunction,  certain Qt5 versions are problematic so knowing what Qt specs have been tested is helpful.

**Comment by Axeia** [comment]
No problem :)
It's been tested with Qt5 and from what I understood the idea is to have PySide2 running alongside PySide6?
