### ISSUE TITLE
Getting wrong colors in preview or the hex is wrong

### ISSUE THREAD

**Issue by MisterMakerNL** [Axeia/FreeCAD-Color-Fetcher#2]
Had some time to screw around with this cool tool! 
Saw that it 's didn't show the correct colors. Not sure what is wrong the hex or the preview.
Seem like it is not with all colors.
![s7fdkfY](https://github.com/Axeia/FreeCAD-Color-Alterator/assets/29804962/8b994a22-821d-48b8-a3e7-18c2654fb3c2)

**Comment by Axeia** [comment]
From a first look it seems like this is a color with Alpha Transparency.
Did you set this through the default FreeCAD UI initially? I had ruled alpha transparency out as a possibility as I didn't think FreeCAD used it anywhere but looks like it does for you at least.

1684340528 would translate to #6464FF30 (note the last two digits not being FF and thus actually having an Alpha channel).
So the cause is easy enough to track down but I'm not quite sure if it should be supported.

**Comment by Axeia** [comment]
I've taken the cautious route to only show QColorDialog with the alpha channel in a test build with Alpha channel IF if it initially has one.
However it might be better to always shows the alpha channel for experimenting? I'd like some feedback on this.

**Comment by Axeia** [comment]
After discussing it a bit on Discord I've decided to leave the cautious approach in place but will add the feature of still being able to edit the alpha channel if it isn't initially set by holding ctrl+shift whilst clicking.

This should prevent accidental access / possible issues whilst allowing those that like experimenting (relatively) easy access.
