### ISSUE TITLE
[Feature request] Color settings for backgrounds

### ISSUE THREAD

**Issue by NXTler** [Axeia/FreeCAD-Color-Fetcher#3]
Hello,
is it possible to make the backgrounds (model tree background, for example) changeable?

Many thanks in advance!

**Comment by Axeia** [comment]
Mmh think I missunderstood this request initially and it resulted in a new feature haha. You can now set the background color of the Tree inside the macro (after an update).

If I'm understanding you right this time around, I guess you mean the tree under Combo View > Model? 
That would be part of the stylesheet you have active. `QTreeView` or `QTreeWidget` specifically. (Or one of the children in it like QTreeWidgetItem). 
As those are part of the stylesheet of the theme you're using they're out of the scope of this project. You have to edit the stylesheet you're using (or start using a stylesheet as otherwise it can't be done), I do however have another macro to make that more of a streamlined process allowing you to refresh the stylesheet in one click:
https://github.com/Axeia/FreeCAD-Stylesheet-Reloading-Macro

**Comment by NXTler** [comment]
Sorry for my poor writing skills, but thanks for the new feature. As you understood correctly I would like to have some kind of way to change the stylesheets background color. But I guess we can leave this to [this new feature](https://github.com/FreeCAD/FreeCAD/pull/10238#issuecomment-1683951824) for the stylesheet devs.

Many thanks anyway!
